FROM node:14

# Create app directory
WORKDIR /usr/src/backend

# Install app dependencies
# A wildcard is used to ensure both package.json AND package-lock.json are copied
# where available (npm@5+)
# COPY package*.json .

# RUN yarn install
# If you are building your code for production
# RUN npm ci --only=production

# Bundle app source
# We don't copy and instead map the volume for hot reloaind in development
# COPY . .

EXPOSE 8080 8081
CMD [ "yarn", "start:dev" ]